const cardData = [
  {
    title: 'CLEVER COUNSEL',
    subtitle: 'LEGAL SERVICE PLATFORM',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    stack: 'React, Node, Python',
    cover: '/clever-counsel.jpg',
    img_1: '/generic-background.png',
    img_2: '/generic-background.png',
    img_3: '/generic-background.png',
    flipped: true,
  },
  {
    title: 'NUMBERS API',
    subtitle: 'TRIVIA RESOURCE',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    stack: 'JavaScript, Python, Express',
    github_url: 'https://github.com/rithmschool/numbers_api',
    demo_url: 'https://google.com/',
    cover: '/numbers-api.jpg',
    img_1: '/generic-background.png',
    img_2: '/generic-background.png',
    img_3: '/generic-background.png',
    flipped: false,
  },
  {
    title: 'JOBLY',
    subtitle: 'PROFESSIONAL NETWORK',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    stack: 'React, Express, Redux, PostgreSQL',
    github_url: 'https://github.com/martinjwkim/react-jobly',
    demo_url: 'https://google.com/',
    cover: '/jobly.jpeg',
    img_1: '/generic-background.png',
    img_2: '/generic-background.png',
    img_3: '/generic-background.png',
    flipped: true,
  },
  {
    title: 'WARBLER',
    subtitle: 'SOCIAL NETWORK',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    stack: 'Python, Flask, PostgreSQL',
    github_url: 'https://github.com/martinjwkim/warbler',
    demo_url: 'https://google.com/',
    cover: '/warbler.jpeg',
    img_1: '/generic-background.png',
    img_2: '/generic-background.png',
    img_3: '/generic-background.png',
    flipped: false,
  },
  {
    title: 'CRYPTO TICKER',
    subtitle: 'INVESTMENT TRACKER',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    stack: 'Python, Docker',
    github_url: 'https://github.com/martinjwkim/cryptoticker',
    cover: '/crypto-ticker.png',
    img_1: '/generic-background.png',
    img_2: '/generic-background.png',
    img_3: '/generic-background.png',
    flipped: true,
  },
];

export default cardData;