const cardData = [
  {
    title: 'Clever Counsel',
    description: 'lorem ipsum blah blah',
    stack: 'React, Node.js, Python/Flask, MySQL, CSS/Bootstrap',
    github_url: 'https://github.com/',
    demo_url: 'https://google.com/',
    cover: 'url(/generic-background.png)',
    img_1: '/generic-background.png',
    img_2: '/generic-background.png',
    img_3: '/generic-background.png',
  },
  {
    title: 'Numbers API',
    description: 'lorem ipsum blah blah',
    stack: 'React, Node.js, Python/Flask, MySQL, CSS/Bootstrap',
    github_url: 'https://github.com/',
    demo_url: 'https://google.com/',
    cover: 'url(/generic-background.png)',
    img_1: '/generic-background.png',
    img_2: '/generic-background.png',
    img_3: '/generic-background.png',
  },
  {
    title: 'Jobly',
    description: 'lorem ipsum blah blah',
    stack: 'React, Node.js, Python/Flask, MySQL, CSS/Bootstrap',
    github_url: 'https://github.com/',
    demo_url: 'https://google.com/',
    cover: 'url(/generic-background.png)',
    img_1: '/generic-background.png',
    img_2: '/generic-background.png',
    img_3: '/generic-background.png',
  },
  {
    title: 'Warbler',
    description: 'lorem ipsum blah blah',
    stack: 'React, Node.js, Python/Flask, MySQL, CSS/Bootstrap',
    github_url: 'https://github.com/',
    demo_url: 'https://google.com/',
    cover: 'url(/generic-background.png)',
    img_1: '/generic-background.png',
    img_2: '/generic-background.png',
    img_3: '/generic-background.png',
  },
  {
    description: 'lorem ipsum blah blah',
    title: 'Crypto Ticker',
    stack: 'React, Node.js, Python/Flask, MySQL, CSS/Bootstrap',
    github_url: 'https://github.com/',
    cover: 'url(/generic-background.png)',
    img_1: '/generic-background.png',
    img_2: '/generic-background.png',
    img_3: '/generic-background.png',
  },
  {
    description: 'lorem ipsum blah blah',
    title: 'More',
    stack: 'React, Node.js, Python/Flask, MySQL, CSS/Bootstrap',
    github_url: 'https://github.com/',
    cover: 'url(/generic-background.png)',
    img_1: 'url(/generic-background.png)',
    img_2: 'url(/generic-background.png)',
    img_3: 'url(/generic-background.png)',
  }
];

export default cardData;